config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  #show is just like a get method
  # index is used for  listing features
  # create is used to insert the entry to the db
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]

  #below code expose all the rest-ful routes for our articles resources
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 6, maximum: 100}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }

  #To validate the email pattern
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: {with: VALID_EMAIL_REGEX}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
    # byebug

  end

  def index
    #This article must be instance variable because we have to other parts of application also.
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit

  end

  def create
    #Below line says that require the top level key of article and permit title and description from their to be
    # used to create this article object or article instance variable.
    @article = Article.new(article_params)
    #Below line is write in lecture 130 because we have to create authentication but here we hardcode the user_id
    # for every article.
    @article.user = User.first
    #Below render method is used to print the result into the browser
    # render plain: @article.inspect
    if @article.save
      # rails provides a flash helper to display the message
      # There are two different types of key used in flash 1. notice 2. alert
      # alert is generally used when something goes wrong.
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else
      render 'new'
    end
    #Below statement generates the url: http://localhost:3000/articles/29  where '29' is id of last article saved.
  end

  def update

    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy

    @article.destroy
    # It generates the URL for the "index" action of the "articles" controller.
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <%@article.errors.full_messages.each do |msg| %>
      <li><%=msg %></li>
    <%end %>
  </ul>
<%end %>

<!--To prefill the information of description according to title given by user -->
<%= form_with(model: @article, local: true) do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <!--    I think f.submit call the update method in article_controller because of form_with helper-->
    <%= f.submit %>
  </p>

<%end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Cancel and return to articles listing', articles_path %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
<!--        below code is accomplish the delete data-->
<!--        here rails is smart enough that means article_path(article) return the id of the article-->
<!--        Here 'delete' is a verb. delete is used because the url of 'show' and 'delete' is same due to this we have to specify very here.-->
        <td><%=link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
<!--        Add confirmation message before delete the article-->
        <td><%= link_to 'Delete', article_path(article), method: :delete, data: { Confirm: "Are you sure?"} %></td>
      </tr>
      <%end %>
  </tbody>
</table>

<p>
  <%= link_to 'Create new article', new_article_path %>
</p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<%=link_to 'Return to article listing', articles_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>

<%= link_to 'Edit', edit_article_path %>
<!--Add confirmation message before delete the article-->
<%= link_to 'Delete', articles_path(@article), method: :delete, data: { Confirm: "Are you sure?"} %>
<%= link_to 'Return to articles listing', articles_path %>

app/views/layouts/_messages.html.erb
<%flash.each do |name, msg| %>
  <%=msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<%= link_to 'Articles listing', articles_path %> |
<%= link_to'Home page', root_path %>

app/views/pages/home.html.erb
<h1>This is the home page</h1>

<%= link_to 'Articles listing', articles_path %> |
<%= link_to'About page', about_path %>